#!/usr/bin/env ruby
require 'socket'
require 'yaml'
require 'fileutils'

path = File.expand_path(File.dirname(__FILE__) + '/../config/mail_receiver.yml')
options = YAML.load_file(path)

host = options['host'] || options[:host] || 'localhost'
port = options['port'] || options[:port] || 12346

mail = $stdin.read


temp_dir = File.expand_path(File.dirname(__FILE__) + '/../tmp/mail')
FileUtils.mkdir_p temp_dir

begin
  temp_path = nil
  3.times do |i|
    now = Time.now
    temp_path = "%s/%d.%05d" % [temp_dir, now.tv_sec, now.tv_usec]
    begin
      File.open(temp_path, File::WRONLY|File::CREAT|File::EXCL){|f| f.write(mail) }
      break
    rescue Errno::EEXIST
      exit(1) if i == 3
      sleep rand
      next
    end
  end

  TCPSocket.open(host, port){|conn|
    conn.write(mail)
  }
rescue
  $stderr.puts $!.message, $!.backtrace
else
  File.unlink(temp_path)
end
