#!/usr/bin/env ruby
require 'socket'
require 'yaml'

path = File.expand_path(File.dirname(__FILE__) + '/../config/mail_receiver.yml')
options = YAML.load_file(path)

host = options['host'] || options[:host] || 'localhost'
port = options['port'] || options[:port] || 12346
begin
  TCPSocket.open(host, port){|conn| }
  puts "successfully connected"
rescue
  $stderr.puts $!.message, $!.backtrace
end
